// DIVI brand kit: self-contained HTML per asset → headless Chrome (absolute file:// URL) → PNG in brand/.
// Paper / ink / gold. Instrument Serif + Inter Tight. CSS gold coins.
'use strict';
const fs = require('fs'); const path = require('path'); const { execFileSync } = require('child_process');
const CHROME = process.env.CHROME || 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const OUT = path.join(__dirname, '..', 'brand'); const TMP = path.join(__dirname, 'out'); fs.mkdirSync(OUT, { recursive: true }); fs.mkdirSync(TMP, { recursive: true });
const FONTS = `<link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter+Tight:wght@400;500;600;700&display=swap" rel="stylesheet">`;
const BASE = `*{margin:0;padding:0;box-sizing:border-box}:root{--paper:#f6f3ee;--paper2:#efeae0;--ink:#151412;--ink2:#4a463f;--ink3:#8a847a;--line:#e3ddd0;--gold:#e5c158;--goldDeep:#a37d12;--green:#1f7a4d;--red:#b3342a}
body{font-family:'Inter Tight',sans-serif;color:var(--ink);background:var(--paper);overflow:hidden}
.serif{font-family:'Instrument Serif',Georgia,serif;font-weight:400}.i{font-style:italic;color:var(--goldDeep)}
.eyebrow{font:500 13px/1 'Inter Tight';letter-spacing:.2em;text-transform:uppercase;color:var(--ink3)}
.coin{position:absolute;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fff2b0,#e5c158 38%,#b8901f 70%,#8a6a12);box-shadow:0 22px 44px -14px rgba(120,90,10,.6),inset 0 -8px 14px rgba(0,0,0,.28),inset 0 8px 12px rgba(255,255,255,.5);display:flex;align-items:center;justify-content:center;font-family:'Instrument Serif',serif;font-style:italic;color:#5c4508}
.coin::after{content:"";position:absolute;inset:8%;border-radius:50%;border:1.5px dashed rgba(90,70,10,.45)}
.coin.edge{background:linear-gradient(90deg,#8a6a12,#e5c158 50%,#8a6a12);border-radius:40%/50%;box-shadow:0 18px 30px -14px rgba(0,0,0,.5)}
.card{position:absolute;border-radius:24px;background:linear-gradient(160deg,#fffdf7,#f3eee2);border:1px solid var(--line);box-shadow:0 30px 60px -30px rgba(40,30,0,.35);padding:24px}
.card .tk{font-family:'Instrument Serif',serif;font-size:56px;line-height:1;letter-spacing:-.03em}.card .k{font:500 10px/1.3 'Inter Tight';letter-spacing:.14em;text-transform:uppercase;color:var(--ink3)}.card .v{font-family:'Instrument Serif',serif;font-size:22px;margin-top:4px}
.pill{display:inline-block;font:600 12px 'Inter Tight';padding:6px 12px;border-radius:20px;background:#e3f2ea;color:var(--green)}
.side{position:absolute;border-radius:24px;background:var(--paper2);border:1px solid var(--line);padding:26px}
.side .lab{font:500 11px/1 'Inter Tight';letter-spacing:.2em;text-transform:uppercase;color:var(--ink3)}.side .big{font-family:'Instrument Serif',serif;font-size:58px;line-height:1;margin:10px 0 6px}.side .num{font:500 26px 'Inter Tight';letter-spacing:-.02em}`;
const coin = (x, y, s, rot, txt) => `<div class="coin" style="left:${x}px;top:${y}px;width:${s}px;height:${s}px;font-size:${s * .5}px;transform:rotate(${rot}deg)">${txt === undefined ? '$' : txt}</div>`;
const edge = (x, y, w, h, rot) => `<div class="coin edge" style="left:${x}px;top:${y}px;width:${w}px;height:${h}px;transform:rotate(${rot}deg)"></div>`;
const pile = (ox, oy, k) => [coin(ox + 210, oy + 10, 150 * k, -18), coin(ox + 60, oy + 120, 120 * k, 12), edge(ox + 330, oy + 200, 130 * k, 44 * k, -8), coin(ox + 150, oy + 230, 170 * k, 6), edge(ox + 20, oy + 320, 120 * k, 40 * k, 5), coin(ox + 340, oy + 290, 110 * k, -30), edge(ox + 200, oy + 380, 150 * k, 46 * k, 2)].join('');
const A = {
  'divi-pfp': [400, 400, `<div style="width:400px;height:400px;position:relative;background:var(--ink)">${coin(80, 80, 240, -12)}<div class="serif" style="position:absolute;left:0;right:0;bottom:26px;text-align:center;font-size:44px;color:var(--paper);letter-spacing:-.02em">DIVI</div></div>`],
  'divi-pfp-paper': [400, 400, `<div style="width:400px;height:400px;position:relative">${coin(80, 62, 240, -12)}<div class="serif" style="position:absolute;left:0;right:0;bottom:30px;text-align:center;font-size:48px;letter-spacing:-.02em">DIVI</div></div>`],
  'divi-wordmark': [1200, 400, `<div style="width:1200px;height:400px;position:relative;display:flex;align-items:center;justify-content:center;gap:34px">${coin(300, 110, 180, -12)}<div style="margin-left:250px"><div class="serif" style="font-size:180px;line-height:1;letter-spacing:-.03em">DIVI</div><div class="eyebrow" style="margin-top:8px">Perps that pay dividends · Robinhood Chain</div></div></div>`],
  'divi-banner': [1500, 500, `<div style="width:1500px;height:500px;position:relative;padding:70px 80px"><div class="eyebrow">Robinhood Chain · USDG · 24/7</div><div class="serif" style="font-size:120px;line-height:.92;letter-spacing:-.025em;margin-top:22px">Perps that pay<br><span class="i">dividends.</span></div><div style="font-size:21px;color:var(--ink2);max-width:600px;margin-top:24px;line-height:1.45">Shorts pay it. Longs receive it. On the ex-date, pro rata by shares. Nothing minted, nothing subsidised.</div><div class="eyebrow" style="margin-top:26px;color:var(--ink)">divionrh.xyz · $DIVI</div>${pile(900, 20, 1.1)}</div>`],
  'divi-og': [1200, 630, `<div style="width:1200px;height:630px;position:relative;padding:70px 80px"><div class="eyebrow">DIVI · Robinhood Chain · USDG · 24/7</div><div class="serif" style="font-size:118px;line-height:.92;letter-spacing:-.025em;margin-top:24px">Long a stock perp.<br>Get paid like a<br><span class="i">shareholder.</span></div><div class="eyebrow" style="margin-top:34px;color:var(--ink)">divionrh.xyz · $DIVI</div>${pile(760, 150, .9)}</div>`],
  'divi-how': [1200, 675, `<div style="width:1200px;height:675px;position:relative;padding:56px 70px"><div class="eyebrow">How it works</div><div class="serif" style="font-size:70px;line-height:.95;letter-spacing:-.02em;margin-top:12px">The dividend <span class="i">moves.</span></div>
    <div class="side" style="left:70px;top:230px;width:330px;height:300px"><div class="lab">Short · 5× AAPL</div><div class="big" style="color:var(--red)">Owes</div><div class="num" style="margin-top:70px">−$4.23</div><div class="lab" style="margin-top:8px">15.67 shares × $0.27</div></div>
    <div class="side" style="left:800px;top:230px;width:330px;height:300px"><div class="lab">Long · 5× AAPL</div><div class="big" style="color:var(--green)">Receives</div><div class="num" style="margin-top:70px">+$4.21</div><div class="lab" style="margin-top:8px">15.58 shares × $0.27</div></div>
    <div style="position:absolute;left:420px;right:420px;top:380px;height:1px;background:repeating-linear-gradient(90deg,#cfc7b6 0 8px,transparent 8px 16px)"></div>${coin(548, 330, 104, 0)}
    <div class="serif" style="position:absolute;left:70px;bottom:56px;font-size:26px;max-width:1060px;color:var(--ink2)">On the ex-date the short’s margin is debited shares × dividend. The cash lands in the long’s free balance. Price gapped down, cash came in — <span class="i">net, a shareholder.</span> The pool only carries its net exposure, which the gap offsets.</div></div>`],
  'divi-vs': [1200, 675, `<div style="width:1200px;height:675px;position:relative;padding:56px 70px"><div class="eyebrow">Ex-dividend date · AAPL pays $0.27</div><div class="serif" style="font-size:70px;line-height:.95;letter-spacing:-.02em;margin-top:12px">Every other perp <span class="i">forgets the dividend.</span></div>
    <div class="card" style="left:70px;top:230px;width:500px;height:330px;background:#fff"><div class="k">Other perps</div><div class="serif" style="font-size:40px;margin:8px 0 18px">Long eats the gap</div><div style="font-size:17px;color:var(--ink2);line-height:1.6">Stock gaps down $0.27 at the open.<br>Long: <b style="color:var(--red)">−$4.21</b>, receives nothing.<br>Short: <b style="color:var(--green)">+$4.23</b>, pays nothing.<br><span style="color:var(--ink3)">Quietly worse than owning the stock.</span></div></div>
    <div class="card" style="left:630px;top:230px;width:500px;height:330px;border:2px solid var(--ink)"><div class="k">DIVI</div><div class="serif" style="font-size:40px;margin:8px 0 18px">The dividend settles</div><div style="font-size:17px;color:var(--ink2);line-height:1.6">Same gap, then the record settles on-chain.<br>Long: −$4.21 gap <b style="color:var(--green)">+ $4.21 cash</b> = a shareholder.<br>Short: +$4.23 gap <b style="color:var(--red)">− $4.23 cash</b> = a real short.<br><span style="color:var(--ink3)">Anyone can settle. Settler keeps 1%.</span></div>${coin(400, 220, 84, -10)}</div>
    <div class="eyebrow" style="position:absolute;left:70px;bottom:50px;color:var(--ink)">divionrh.xyz · $DIVI</div></div>`],
  'divi-board': [1200, 675, `<div style="width:1200px;height:675px;position:relative;padding:56px 70px"><div class="eyebrow">Day one</div><div class="serif" style="font-size:70px;line-height:.95;letter-spacing:-.02em;margin-top:12px">Eleven names. <span class="i">Every payday.</span></div>
    ${[['AAPL', 'Apple', '0.34%'], ['MSFT', 'Microsoft', '0.73%'], ['JNJ', 'J&J', '1.92%'], ['IBM', 'IBM', '2.83%'], ['MCD', "McDonald's", '2.83%'], ['COST', 'Costco', '0.64%'], ['SPY', 'S&P 500', '0.97%'], ['META', 'Meta', '0.34%']].map((r, i) => `<div class="card" style="left:${70 + (i % 4) * 268}px;top:${230 + Math.floor(i / 4) * 190}px;width:248px;height:170px;padding:18px"><div class="tk" style="font-size:44px">${r[0]}</div><div class="k" style="margin-top:4px">${r[1]}</div><div style="margin-top:22px;display:flex;justify-content:space-between;align-items:end"><div><div class="k">Yield</div><div class="v">${r[2]}</div></div><span class="pill">pays</span></div></div>`).join('')}
    <div class="eyebrow" style="position:absolute;left:70px;bottom:36px;color:var(--ink)">+ NVDA · GOOGL · QQQ · real Robinhood Chain pools · divionrh.xyz</div></div>`],
};
for (const [name, [w, h, body]] of Object.entries(A)) {
  const f = path.join(TMP, name + '.html'); fs.writeFileSync(f, `<!doctype html><html><head><meta charset="utf-8">${FONTS}<style>${BASE}html,body{width:${w}px;height:${h}px}</style></head><body>${body}</body></html>`);
  execFileSync(CHROME, ['--headless=new', '--disable-gpu', '--no-sandbox', '--hide-scrollbars', '--force-device-scale-factor=1', `--window-size=${w},${h}`, '--virtual-time-budget=6000', `--screenshot=${path.join(OUT, name + '.png')}`, 'file:///' + f.split(String.fromCharCode(92)).join('/')], { stdio: 'ignore' });
  console.log('✓', name + '.png');
}
